### ISSUE TITLE
Ideare la struttura di categorie/sezioni per GH Discussions

### ISSUE THREAD

**Issue by Mirio** [DevOpsItalia/devopsitalia.github.io#3]
Ideare la struttura di categorie/sezioni per GH Discussions

**Comment by kalos** [comment]
Ecco le categorie che metterei:
- Generale
- Linux
- Kubernetes
- IaC
- Cloud
- Idee

Altre categorie, magari da aggiungere in futuro se diventano argomenti interessanti:

- CI/CD e GitOps
- Container
- Monitoring/Observation
- Virtualization
- Storage
- Networking
- Infosec
- Log Management
- Backup

**Comment by Mirio** [comment]
Io ne promuoverei direttamente alcune per avere sin da subito quanto segue:

- Generale
- Containers/Kubernetes
- Monitoring/Observation
- CI/CD e GitOps
- IaC
- Cloud
- Idee

Che ne pensate?

**Comment by Kavuti** [comment]
Mi sembra che la lista di @Mirio sia abbastanza esaustiva. Escludere monitoring o CI/CD non mi fa impazzire come idea.

**Comment by Q3Neo** [comment]
Quoto @Kavuti , la versione di @Mirio mi sembra la più esaustiva, fermo restando che in futuro si potranno comunque aggiungere delle sezioni se dovesse sentirsene la mancanza.

**Comment by kalos** [comment]
Categorie create
