### ISSUE TITLE
Scegliere e comparare il framework per static page

### ISSUE THREAD

**Issue by Mirio** [DevOpsItalia/devopsitalia.github.io#4]
Scegliere e comparare il framework per la parte di blogging che sia statico, facilmente gestibile e scalabile

**Comment by kalos** [comment]
io sarei per utilizzare qualcosa di molto minimale, come hugo con un tema adatto per la documentazione, come https://themes.gohugo.io/themes/hugo-theme-relearn/

**Comment by Mirio** [comment]
+1 per Hugo come static generator

**Comment by Q3Neo** [comment]
Nella mia esperienza mi ero trovato molto bene con Docosaurus, come pregi avevo riscontrato:
- facilità di installazione 
- utilizzo intuitivo basato sulla gerarchia dei file e delle cartelle
- integrazione elementare  all'interno di processi automatizzati (pipelines/github actions)

Conosco Hugo solo di nome e quando provai a utilizzarlo nel 2018 non avevo riscontrato i medesimi vantaggi ma mi fido della vostra esperienza se decidiamo di utilizzare questo tool

**Comment by kalos** [comment]
per i commenti si potrebbe usare https://giscus.app anzichè disquis

**Comment by Mirio** [comment]
> per i commenti si potrebbe usare https://giscus.app anzichè disquis

Sembra molto carino, sicuramente è da approfondire!

**Comment by ptx96** [comment]
Io ho esperienza con Vue / Vite, per cui guarderei a [VuePress](https://v2.vuepress.vuejs.org/) o [VitePress](https://vitepress.dev/).

---

Se però abbiamo una conoscenza comune più incentrata su Hugo, va benissimo anche quello.

Per quanto riguarda lo stile, preferirei andare più verso un "Blog", senza perdere di vista il lato tags, documentazione e archivio;
per capirci, una cosa di questo genere: [Fixit Hugo Theme](https://themes.gohugo.io/themes/fixit/).

Inoltre questo tema, tra le altre cose, è compatibile out of the box con il comment system [giscus](https://giscus.app/) sopramenzionato.

**Comment by Mirio** [comment]
> Io ho esperienza con Vue / Vite, per cui guarderei a [VuePress](https://v2.vuepress.vuejs.org/) o [VitePress](https://vitepress.dev/).
> 
> Se però abbiamo una conoscenza comune più incentrata su Hugo, va benissimo anche quello.

Io inizierei con Hugo e poi eventualmente mi terrei da parte framework più complessi basati su VUE o simili.

> Per quanto riguarda lo stile, preferirei andare più verso un "Blog", senza perdere di vista il lato tags, documentazione e archivio; per capirci, una cosa di questo genere: [Fixit Hugo Theme](https://themes.gohugo.io/themes/fixit/).
> 
> Inoltre questo tema, tra le altre cose, è compatibile out of the box con il comment system [giscus](https://giscus.app/) sopramenzionato.

+1 Per il tema
